[[plugins]]
#  統合ユーザインターフェース
#  参考：http://mba-hack.blogspot.jp/2013/03/unitevim.html
repo = 'Shougo/unite.vim'

[[plugins]]
# Unite上で簡単にcolorscheme のプレビューを確認
repo = 'ujihisa/unite-colorscheme'
# unite.vim を読み込んだら一緒に読み込む
on_source = ['unite.vim']

[[plugins]]
# アウトライン
repo = 'h1mesuke/unite-outline'
# unite.vim を読み込んだら一緒に読み込む
on_source = ['unite.vim']

[[plugins]]
# 補完プラグイン
repo = 'Shougo/neocomplete.vim'
# インサートモードに入ったら読み込む
on_i = 1

[[plugins]]
# スニペット補完プラグイン
repo = 'Shougo/neosnippet'
on_i = 1

[[plugins]]
# 各種スニペット
repo = 'Shougo/neosnippet-snippets'
on_source = ['neosnippet']

# [[plugins]]
# GO言語
# repo = 'fatih/vim-go'
# on_ft = ['go']

# [[plugins]]
# GO言語(tag)
# repo = 'jstemmer/gotags'
# on_ft = ['go']

[[plugins]]
# yaml軽量
repo = 'stephpy/vim-yaml'
on_ft = ['yaml']

[[plugins]]
# Python 補完
repo = 'davidhalter/jedi-vim'
on_ft = ['pyrhon']

[[plugins]]
# jsdoc 形式を挿入
repo = 'heavenshell/vim-jsdoc'
on_ft = ['javascript']

[[plugins]]
# JavaScriptのシンタックス
repo = 'jelera/vim-javascript-syntax'
on_ft = ['javascript']

[[plugins]]
# javascript のインデント
repo = 'pangloss/vim-javascript'
on_ft = ['javascremmetipt']

[[plugins]]
# jQueryのシンタックス
repo = 'vim-scripts/jQuery'
on_ft = ['javascript']

[[plugins]]
# jshint連携
repo = 'walm/jshint.vim'
on_ft = ['javascript']

[[plugins]]
# Better json
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
# JSONの整形
repo = '5t111111/neat-json.vim'
on_ft = ['json']

[[plugins]]
# VimでMarkdown
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
# markdownをプレビューする(1/2)
repo = 'kannokanno/previm'
on_ft = ['markdown']

[[plugins]]
# markdownをプレビューする(2/2)
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']

# [[plugins]]
# htmlシンタックス
# repo = 'othree/html5.vim'
# on_ft = ['html']

[[plugins]]
# cssシンタックス
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
# TypeScript IDE.
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']
